In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time

def scrape_detik_news():
    base_url = "https://news.detik.com"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    try:
        response = requests.get(base_url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari artikel berita
        articles = soup.find_all('article', class_='list-content__item')
        
        news_data = []
        for article in articles[:10]:  # Ambil 10 berita pertama
            # try:
            title_elem = article.find('h3', class_='media__title')
            if not title_elem:  # Skip jika tidak ada h3
                print("Skipping article: No title element found")
                continue

            title = title_elem.find('a').text.strip() if title_elem else 'N/A'
            # a_tag = title_elem.find('a').text.strip() if a_tag else 'N/A'
                
            # link_elem = article.find('h3', class_='media__title').find('a')
                
            link = title_elem['href'] if title_elem else 'N/A'
                # link = link_elem['href'] if link_elem else 'N/A'
                
            time_elem = article.find('div', class_='media__date')
            publish_time = time_elem.text.strip() if time_elem else 'N/A'
                
            # summary_elem = article.find('div', class_='media__desc')
                # summary = summary_elem.text.strip() if summary_elem else 'N/A'
                
            news_data.append({
                'title': title,
                'link': link,
                'publish_time': publish_time,
                # 'summary': summary,
                'scraped_at': datetime.now().isoformat()
                })
            
            # except Exception as e:
            #     print(f"Error parsing article: {e}")
            #     continue
        
        # Convert to DataFrame
        df = pd.DataFrame(news_data)
        return df
        
    except Exception as e:
        print(f"Error scraping Detik: {e}")
        return None

# Jalankan scraping
news_df = scrape_detik_news()
if news_df is not None:
    print(f"Berhasil scraping {len(news_df)} berita")
    print(news_df.head())
    
    # Simpan ke CSV
    news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')

Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Error scraping Detik: 'href'

In [4]:
news_df

,title,link,publish_time,scraped_at
0,Kiprah KJRI Hong Kong Obati Rindu PMI Terkungk...,https://news.detik.com/berita/d-8146164/kiprah...,3 menit yang lalu,2025-10-06T08:37:58.454734
1,"Tak Hanya di Cirebon, Warga Majalengka Juga Li...",https://news.detik.com/berita/d-8146791/tak-ha...,4 menit yang lalu,2025-10-06T08:37:58.454877
2,4 Pesan Penting Prabowo saat Hadiri HUT TNI,https://news.detik.com/berita/d-8146788/4-pesa...,12 menit yang lalu,2025-10-06T08:37:58.454953

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time

def scrape_detik_news():
    base_url = "https://news.detik.com"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    try:
        response = requests.get(base_url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari artikel berita
        articles = soup.find_all('article', class_='list-content__item')
        
        news_data = []
        for article in articles[:10]:  # Ambil 10 berita pertama
            try:
                # Cari elemen h3 sekali saja, lalu validasi
                title_elem = article.find('h3', class_='media__title')
                if not title_elem:  # Skip jika tidak ada h3
                    print("Skipping article: No title element found")
                    continue
                
                # Ekstrak title dengan check a tag
                a_tag = title_elem.find('a')
                title = a_tag.text.strip() if a_tag else 'N/A'
                
                # Ekstrak link dari a_tag yang sama (lebih efisien)
                link = a_tag['href'] if a_tag else 'N/A'
                
                # Ekstrak waktu
                time_elem = article.find('div', class_='media__date')
                publish_time = time_elem.text.strip() if time_elem else 'N/A'
                
                # summary_elem = article.find('div', class_='media__desc')  # Uncomment jika perlu
                # summary = summary_elem.text.strip() if summary_elem else 'N/A'
                
                news_data.append({
                    'title': title,
                    'link': link,
                    'publish_time': publish_time,
                    # 'summary': summary,
                    'scraped_at': datetime.now().isoformat()
                })
                
            except Exception as e:
                print(f"Error parsing article: {e}")
                continue
        
        # Convert to DataFrame
        df = pd.DataFrame(news_data)
        return df
        
    except Exception as e:
        print(f"Error scraping Detik: {e}")
        return None

# Jalankan scraping
news_df = scrape_detik_news()
if news_df is not None:
    print(f"Berhasil scraping {len(news_df)} berita")
    print(news_df.head())
    
    # Simpan ke CSV
    news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')

Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Skipping article: No title element found
Berhasil scraping 3 berita
                                               title  \
0  Info Lalin di Jalur Arteri Jakarta Pagi Ini: C...
1  Kiprah KJRI Hong Kong Obati Rindu PMI Terkungk...
2  Tak Hanya di Cirebon, Warga Majalengka Juga Li...

                                                link        publish_time  \
0  https://news.detik.com/berita/d-8146814/info-l...  12 menit yang lalu
1  https://news.detik.com/berita/d-8146164/kiprah...  14 menit yang lalu
2  https://news.detik.com/berita/d-8146791/tak-ha...  15 menit yang lalu

                   scraped_at
0  2025-10-06T08:45:20.858512
1  2025-10-06T08:45:20.858578
2  2025-10-06T08:45:20.858616

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time

def scrape_detik_news():
    base_url = "https://news.detik.com"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    try:
        response = requests.get(base_url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari lebih banyak artikel untuk kompensasi skipping
        articles = soup.find_all('article', class_='list-content__item')[:20]  # Ambil 20, ambil 10 valid
        
        news_data = []
        valid_count = 0
        for article in articles:
            # Filter dasar: Harus ada link (a tag) untuk hindari iklan
            a_tag = article.find('a', href=True)
            if not a_tag:
                continue
            
            # Coba cari title_elem (h3 dulu, fallback ke h2)
            title_elem = article.find('h3', class_='media__title') or article.find('h2')
            # if not title_elem:
            #     print("Skipping article: No title element found")
            #     continue
            
            try:
                # Title dari a_tag di dalam title_elem
                title = a_tag.text.strip() if a_tag else 'N/A'
                
                # Link: Buat full URL jika relative
                link = a_tag['href']
                if link.startswith('/'):
                    link = base_url + link
                
                # Waktu
                time_elem = article.find('div', class_='media__date')
                publish_time = time_elem.text.strip() if time_elem else 'N/A'
                
                # # Summary (uncommented dan fixed)
                # summary_elem = article.find('div', class_='media__desc')
                # summary = summary_elem.text.strip() if summary_elem else 'N/A'
                
                news_data.append({
                    'title': title,
                    'link': link,
                    'publish_time': publish_time,
                    # 'summary': summary,
                    'scraped_at': datetime.now().isoformat()
                })
                
                valid_count += 1
                if valid_count >= 10:  # Stop setelah 10 valid
                    break
                    
            except Exception as e:
                print(f"Error parsing article: {e}")
                continue
        
        # Convert to DataFrame
        df = pd.DataFrame(news_data)
        return df
        
    except Exception as e:
        print(f"Error scraping Detik: {e}")
        return None

# Jalankan scraping
news_df = scrape_detik_news()
if news_df is not None:
    print(f"Berhasil scraping {len(news_df)} berita")
    print(news_df.head())
    
    # Simpan ke CSV
    # news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')
    news_df

Berhasil scraping 10 berita
  title                                               link publish_time  \
0        https://news.detik.com/berita/d-8146297/ajudan...          N/A
1        https://news.detik.com/berita/d-8146156/prajur...          N/A
2        https://news.detik.com/berita/d-8146231/menses...          N/A
3        https://news.detik.com/berita/d-8146232/sosok-...          N/A
4        https://news.detik.com/berita/d-8145619/bnpb-u...          N/A

                   scraped_at
0  2025-10-06T08:54:24.880849
1  2025-10-06T08:54:24.880958
2  2025-10-06T08:54:24.881003
3  2025-10-06T08:54:24.881046
4  2025-10-06T08:54:24.881090

In [15]:
news_df

,title,link,publish_time,scraped_at
0,,https://news.detik.com/berita/d-8146297/ajudan...,N/A,2025-10-06T08:54:24.880849
1,,https://news.detik.com/berita/d-8146156/prajur...,N/A,2025-10-06T08:54:24.880958
2,,https://news.detik.com/berita/d-8146231/menses...,N/A,2025-10-06T08:54:24.881003
3,,https://news.detik.com/berita/d-8146232/sosok-...,N/A,2025-10-06T08:54:24.881046
4,,https://news.detik.com/berita/d-8145619/bnpb-u...,N/A,2025-10-06T08:54:24.881090
5,Di Antara Jokowi dan PSI,https://news.detik.com/berita/d-8146822/di-ant...,N/A,2025-10-06T08:54:24.881119
6,Buka-bukaan Istana soal Pertemuan Prabowo dan ...,https://news.detik.com/berita/d-8146750/buka-b...,N/A,2025-10-06T08:54:24.881147
7,,https://news.detik.com/berita/d-8146825/jokowi...,4 menit yang lalu,2025-10-06T08:54:24.881192
8,,https://news.detik.com/berita/d-8146616/kisah-...,7 menit yang lalu,2025-10-06T08:54:24.881233
9,,https://news.detik.com/kolom/d-8146823/pertaha...,8 menit yang lalu,2025-10-06T08:54:24.881277

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time

def scrape_detik_news():
    base_url = "https://www.detik.com/search/searchall"  # Gunakan search page untuk struktur stabil
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    params = {
        'query': '',  # Kosong untuk latest news umum
        'sortby': 'time'
    }
    
    try:
        response = requests.get(base_url, headers=headers, params=params)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari articles lebih luas (semua <article>, seperti di tutorial 2025)
        articles = soup.find_all('article')[:30]  # Ambil 30 untuk kompensasi
        
        news_data = []
        valid_count = 0
        for article in articles:
            # Cari title_elem: Prioritas h3.media__title, fallback h2
            title_elem = article.find('h3', class_='media__title') or article.find('h2', class_='media__title')
            if not title_elem:
                # Fallback lebih luas jika masih gak ada
                title_elem = article.find(['h2', 'h3'])
                if not title_elem:
                    continue
            
            # Ambil a_tag dari title_elem (spesifik untuk title link)
            a_tag = title_elem.find('a')
            if not a_tag:
                continue
            
            # Title dari a_tag text
            title = a_tag.text.strip()
            if not title:  # Skip jika title kosong
                continue
            
            # Link: Full URL
            link = a_tag['href']
            if link.startswith('/'):
                link = 'https://www.detik.com' + link
            
            # Publish time: Cari div.media__date, ambil text (include span.time__text jika ada)
            time_elem = article.find('div', class_='media__date')
            if time_elem:
                # Jika ada span di dalam, ambil dari situ; else text langsung
                time_span = time_elem.find('span', class_='time__text')
                publish_time = time_span.text.strip() if time_span else time_elem.text.strip()
            else:
                publish_time = 'N/A'
            
            # Summary
            summary_elem = article.find('div', class_='media__desc')
            summary = summary_elem.text.strip() if summary_elem else 'N/A'
            
            news_data.append({
                'title': title,
                'link': link,
                'publish_time': publish_time,
                'summary': summary,
                'scraped_at': datetime.now().isoformat()
            })
            
            valid_count += 1
            if valid_count >= 10:  # Stop setelah 10 valid
                break
        
        # Convert to DataFrame
        df = pd.DataFrame(news_data)
        return df
        
    except Exception as e:
        print(f"Error scraping Detik: {e}")
        return None

# Jalankan scraping
news_df = scrape_detik_news()
if news_df is not None:
    print(f"Berhasil scraping {len(news_df)} berita")
    print(news_df.head(10))  # Print 10 untuk lihat semua
    
    # Simpan ke CSV
    # news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')
    news_df

Berhasil scraping 0 berita
Empty DataFrame
Columns: []
Index: []

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

def scrape_detik_news(query='berita', num_articles=10):
    base_url = "https://www.detik.com/search/searchall"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    params = {
        'query': query,
        'sortby': 'time',
        'page': 1
    }
    
    try:
        response = requests.get(base_url, headers=headers, params=params)
        if response.status_code != 200:
            print(f"Error: Status code {response.status_code}")
            return None
        
        soup = BeautifulSoup(response.text, 'html.parser')
        articles = soup.find_all('article')
        
        news_data = []
        count = 0
        for article in articles:
            if count >= num_articles:
                break
            
            # Title: Cari h2
            title_elem = article.find('h2')
            title = title_elem.get_text(strip=True) if title_elem else 'N/A'
            if title == 'N/A':
                continue
            
            # Link: Cari a href=True pertama (dari tutorial)
            link_elem = article.find('a', href=True)
            link = link_elem['href'] if link_elem else 'N/A'
            if link.startswith('/'):
                link = 'https://www.detik.com' + link
            
            # Publish time
            time_elem = article.find('div', class_='media__date')
            publish_time = time_elem.get_text(strip=True) if time_elem else 'N/A'
            
            # Summary
            summary_elem = article.find('div', class_='media__desc')
            summary = summary_elem.get_text(strip=True) if summary_elem else 'N/A'
            
            news_data.append({
                'title': title,
                'link': link,
                'publish_time': publish_time,
                'summary': summary,
                'scraped_at': datetime.now().isoformat()
            })
            
            count += 1
        
        df = pd.DataFrame(news_data)
        return df
        
    except Exception as e:
        print(f"Error scraping Detik: {e}")
        return None

# Jalankan scraping
news_df = scrape_detik_news(query='berita', num_articles=10)
if news_df is not None:
    print(f"Berhasil scraping {len(news_df)} berita")
    print(news_df.head(10))
    
    # Simpan ke CSV
    # news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')
    news_df
else:
    print("Gagal scraping, coba ganti query (misal 'politik' atau 'olahraga')")

Berhasil scraping 10 berita
       title                                               link  \
0  detikNews  https://news.detik.com/internasional/d-8145123...
1  detikNews  https://news.detik.com/internasional/d-8143736...
2  detikNews  https://news.detik.com/internasional/d-8142023...
3    20Detik  https://20.detik.com/detikupdate/20250925-2509...
4  detikNews  https://news.detik.com/internasional/d-8139957...
5  detikNews  https://news.detik.com/internasional/d-8133492...
6  detikNews  https://news.detik.com/internasional/d-8132193...
7  detikNews  https://news.detik.com/internasional/d-8138123...
8  detikNews  https://news.detik.com/internasional/d-8130403...
9  detikNews  https://news.detik.com/internasional/d-8128517...

                    publish_time  \
0   Sabtu, 04 Okt 2025 19:00 WIB
1   Jumat, 03 Okt 2025 17:37 WIB
2   Kamis, 02 Okt 2025 17:56 WIB
3   Kamis, 25 Sep 2025 17:34 WIB
4    Rabu, 01 Okt 2025 17:02 WIB
5   Sabtu, 27 Sep 2025 18:05 WIB
6   Jumat, 26 Sep 2025 18:00 WIB
7  Selasa, 30 Sep 2025 17:30 WIB
8   Kamis, 25 Sep 2025 17:26 WIB
9    Rabu, 24 Sep 2025 17:16 WIB

                                             summary  \
0  Sanae Takaichi terpilih menjadi pemimpin parta...
1  Presiden Rusia Vladimir Putin mengatakan negar...
2  Turki menuduh Israel melakukan "aksi terorisme...
3                                                N/A
4  PM Giorgia Meloni mendesak armada kapal bantua...
5  Netanyahu menyebut negara Palestina akan menja...
6  Netanyahu mengambil penerbangan lebih panjang ...
7  Perdana Menteri (PM) Israel Benjamin Netanyahu...
8  Spanyol akan bergabung dengan Italia dalam men...
9  Media terkemuka Israel menyoroti pidato Presid...

                   scraped_at
0  2025-10-06T08:51:29.312816
1  2025-10-06T08:51:29.312881
2  2025-10-06T08:51:29.312952
3  2025-10-06T08:51:29.313017
4  2025-10-06T08:51:29.313094
5  2025-10-06T08:51:29.313157
6  2025-10-06T08:51:29.313212
7  2025-10-06T08:51:29.313284
8  2025-10-06T08:51:29.313337
9  2025-10-06T08:51:29.313397

In [13]:
news_df

,title,link,publish_time,summary,scraped_at
0,detikNews,https://news.detik.com/internasional/d-8145123...,"Sabtu, 04 Okt 2025 19:00 WIB",Sanae Takaichi terpilih menjadi pemimpin parta...,2025-10-06T08:51:29.312816
1,detikNews,https://news.detik.com/internasional/d-8143736...,"Jumat, 03 Okt 2025 17:37 WIB",Presiden Rusia Vladimir Putin mengatakan negar...,2025-10-06T08:51:29.312881
2,detikNews,https://news.detik.com/internasional/d-8142023...,"Kamis, 02 Okt 2025 17:56 WIB","Turki menuduh Israel melakukan ""aksi terorisme...",2025-10-06T08:51:29.312952
3,20Detik,https://20.detik.com/detikupdate/20250925-2509...,"Kamis, 25 Sep 2025 17:34 WIB",N/A,2025-10-06T08:51:29.313017
4,detikNews,https://news.detik.com/internasional/d-8139957...,"Rabu, 01 Okt 2025 17:02 WIB",PM Giorgia Meloni mendesak armada kapal bantua...,2025-10-06T08:51:29.313094
5,detikNews,https://news.detik.com/internasional/d-8133492...,"Sabtu, 27 Sep 2025 18:05 WIB",Netanyahu menyebut negara Palestina akan menja...,2025-10-06T08:51:29.313157
6,detikNews,https://news.detik.com/internasional/d-8132193...,"Jumat, 26 Sep 2025 18:00 WIB",Netanyahu mengambil penerbangan lebih panjang ...,2025-10-06T08:51:29.313212
7,detikNews,https://news.detik.com/internasional/d-8138123...,"Selasa, 30 Sep 2025 17:30 WIB",Perdana Menteri (PM) Israel Benjamin Netanyahu...,2025-10-06T08:51:29.313284
8,detikNews,https://news.detik.com/internasional/d-8130403...,"Kamis, 25 Sep 2025 17:26 WIB",Spanyol akan bergabung dengan Italia dalam men...,2025-10-06T08:51:29.313337
9,detikNews,https://news.detik.com/internasional/d-8128517...,"Rabu, 24 Sep 2025 17:16 WIB",Media terkemuka Israel menyoroti pidato Presid...,2025-10-06T08:51:29.313397

# Notebook Praktikum

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time

def scrape_detik_news():
    base_url = "https://news.detik.com"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    try:
        response = requests.get(base_url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari artikel berita
        articles = soup.find_all('article', class_='list-content__item')
        # print(articles[:10])
        articles_h3 = [a for a in articles if a.find('h3', class_='media__title')]
        
        news_data = []
        for article in articles_h3[:]:  # Ambil 10 berita pertama
            try:
                title_elem = article.find('h3', class_='media__title')
                title = title_elem.find('a').text.strip() if title_elem else 'N/A'
                
                # link_elem = article.find('h3', class_='media__title').find('a')
                link_elem = article.find('h3', class_='media__title').find('a')
                # link = link_elem['href'] if link_elem else 'N/A'
                link = link_elem['href'] if link_elem else 'N/A'
                
                time_elem = article.find('div', class_='media__date')
                publish_time = time_elem.text.strip() if time_elem else 'N/A'
                
                # summary_elem = article.find('div', class_='media__desc')
                # summary = summary_elem.text.strip() if summary_elem else 'N/A'
                
                news_data.append({
                    'title': title,
                    'link': link,
                    'publish_time': publish_time,
                    # 'summary': summary,
                    'scraped_at': datetime.now().isoformat()
                })
                
            except Exception as e:
                print(f"Error parsing article: {e}")
                continue
        
        # Convert to DataFrame
        df = pd.DataFrame(news_data)
        return df
        
    except Exception as e:
        print(f"Error scraping Detik: {e}")
        return None

# Jalankan scraping
news_df = scrape_detik_news()
news_df
    
    # Simpan ke CSV
    # news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')

,title,link,publish_time,scraped_at
0,"Disaksikan Prabowo, Jaksa Agung Serahkan 6 Sme...",https://news.detik.com/berita/d-8147069/disaks...,1 menit yang lalu,2025-10-06T11:31:19.844272
1,Tim SAR Sempat Terserang Gatal-gatal Saat Evak...,https://news.detik.com/berita/d-8147066/tim-sa...,3 menit yang lalu,2025-10-06T11:31:19.844653
2,Aktivis Global Flotilla Beberkan Kekejaman Isr...,https://news.detik.com/internasional/d-8147053...,5 menit yang lalu,2025-10-06T11:31:19.844715
3,"PAM JAYA Gelar Bazar Gratis di Pademangan, Had...",https://news.detik.com/berita/d-8147044/pam-ja...,6 menit yang lalu,2025-10-06T11:31:19.844783
4,"Kisah Pilu Hadijah, Penderita Cerebral Palsy y...",https://news.detik.com/berita/d-8147042/kisah-...,7 menit yang lalu,2025-10-06T11:31:19.844836
...,...,...,...,...
56,Jenazah Istri Ke-7 Presiden Soekarno Yurike Ma...,https://news.detik.com/foto-news/d-8146410/jen...,N/A,2025-10-06T11:31:19.850759
57,Buka-bukaan Istana soal Pertemuan Prabowo dan ...,https://news.detik.com/berita/d-8146750/buka-b...,N/A,2025-10-06T11:31:19.850868
58,Irma NasDem Sebut SPPG Polri Tak Ada yang Berk...,https://news.detik.com/berita/d-8139674/irma-n...,N/A,2025-10-06T11:31:19.850954
59,Kepala BGN: Instruksi Presiden Seluruh SPPG Ak...,https://news.detik.com/berita/d-8140233/kepala...,N/A,2025-10-06T11:31:19.851021
60,Reaksi Hamas-Warga Palestina Atas 20 Poin Renc...,https://news.detik.com/internasional/d-8136866...,N/A,2025-10-06T11:31:19.851071

In [28]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time

def scrape_detik_news():
    base_url = "https://news.detik.com"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    response = requests.get(base_url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
        
    # Cari artikel berita
    articles = soup.find_all('article', class_='list-content__item')
        
    news_data = []
    for article in articles[:10]:  # Ambil 10 berita pertama
        title_elem = article.find('h3', class_='media__title')
        title = title_elem.find('a').text.strip() if title_elem else 'N/A'
                
        # link_elem = article.find('h3', class_='media__title').find('a')
        link_elem = article.find('h3', class_='media__title').find('a')
        link = link_elem['href'] if link_elem else 'N/A'
                
        time_elem = article.find('div', class_='media__date')
        publish_time = time_elem.text.strip() if time_elem else 'N/A'
                
                # summary_elem = article.find('div', class_='media__desc')
                # summary = summary_elem.text.strip() if summary_elem else 'N/A'
                
        news_data.append({
                    'title': title,
                    'link': link,
                    'publish_time': publish_time,
                    # 'summary': summary,
                    'scraped_at': datetime.now().isoformat()
                })
    
    # Convert to DataFrame
    df = pd.DataFrame(news_data)
    return df

In [29]:
# Jalankan scraping
news_df = scrape_detik_news()
news_df
    
    # Simpan ke CSV
    # news_df.to_csv('detik_news.csv', index=False, encoding='utf-8')

KeyError: 'href'

In [42]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

def scrape_bmkg_weather():
    url = "https://www.bmkg.go.id/cuaca/prakiraan-cuaca-indonesia.bmkg"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari tabel cuaca
        # weather_table = soup.find('table', class_='min-w-full')
        weather_table = soup.find('table', class_='min-w-full')
        print(weather_table)
        
        # if not weather_table:
        #     print("Tabel cuaca tidak ditemukan")
        #     return None
        
        weather_data = []
        rows = weather_table.find_all('tr')[1:]  # Skip header
        
        for row in rows:
            cols = row.find_all('td')
            if len(cols) >= 4:
                city = cols[0].text.strip()
                weather = cols[1].text.strip()
                temp = cols[2].text.strip()
                humidity = cols[3].text.strip()
                
                weather_data.append({
                    'city': city,
                    'weather_condition': weather,
                    'temperature': temp,
                    'humidity': humidity,
                    'scraped_at': datetime.now().isoformat()
                })
        
        df = pd.DataFrame(weather_data)
        return df
        
    except Exception as e:
        print(f"Error scraping BMKG: {e}")
        return None

# Jalankan scraping cuaca
weather_df = scrape_bmkg_weather()
if weather_df is not None:
    print(f"Data cuaca untuk {len(weather_df)} kota")
    print(weather_df.head())

Error scraping BMKG: 'NoneType' object has no attribute 'find_all'

In [41]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

def scrape_bmkg_weather():
    url = "https://www.bmkg.go.id/cuaca/prakiraan-cuaca-indonesia.bmkg"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Cari tabel cuaca
        weather_table = soup.find('table', class_='table-weather')
        
        if not weather_table:
            print("Tabel cuaca tidak ditemukan")
            return None
            
        weather_data = []
        rows = weather_table.find_all('tr')[1:]  # Skip header
        
        for row in rows:
            cols = row.find_all('td')
            if len(cols) >= 4:
                city = cols[0].text.strip()
                weather = cols[1].text.strip()
                temp = cols[2].text.strip()
                humidity = cols[3].text.strip()
                
                weather_data.append({
                    'city': city,
                    'weather_condition': weather,
                    'temperature': temp,
                    'humidity': humidity,
                    'scraped_at': datetime.now().isoformat()
                })
        
        df = pd.DataFrame(weather_data)
        return df
        
    except Exception as e:
        print(f"Error scraping BMKG: {e}")
        return None

# Jalankan scraping cuaca
weather_df = scrape_bmkg_weather()
if weather_df is not None:
    print(f"Data cuaca untuk {len(weather_df)} kota")
    print(weather_df.head())

Tabel cuaca tidak ditemukan

In [45]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

def scrape_bmkg_weather():
    url = "https://www.bmkg.go.id/cuaca/prakiraan-cuaca-indonesia.bmkg"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        tables = soup.find_all('table')
        print(f"Jumlah tabel ditemukan: {len(tables)}")
        for i, table in enumerate(tables):
            print(f"Tabel {i}: class={table.get('class')}, id={table.get('id')}")
        print(soup.prettify()[:2000])
        # # Cari tabel cuaca
        # weather_table = soup.find('table', class_='table-weather')
        
        # if not weather_table:
        #     print("Tabel cuaca tidak ditemukan")
        #     return None
            
        # weather_data = []
        # rows = weather_table.find_all('tr')[1:]  # Skip header
        
        # for row in rows:
        #     cols = row.find_all('td')
        #     if len(cols) >= 4:
        #         city = cols[0].text.strip()
        #         weather = cols[1].text.strip()
        #         temp = cols[2].text.strip()
        #         humidity = cols[3].text.strip()
                
        #         weather_data.append({
        #             'city': city,
        #             'weather_condition': weather,
        #             'temperature': temp,
        #             'humidity': humidity,
        #             'scraped_at': datetime.now().isoformat()
        #         })
        
        # df = pd.DataFrame(weather_data)
        # return df
        
    except Exception as e:
        print(f"Error scraping BMKG: {e}")
        return None

# Jalankan scraping cuaca
weather_df = scrape_bmkg_weather()
if weather_df is not None:
    print(f"Data cuaca untuk {len(weather_df)} kota")
    print(weather_df.head())

Jumlah tabel ditemukan: 0
<!DOCTYPE html>
<html data-capo="" lang="id">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <style nonce="kZMRWxkPsoK5GegRY0sYU1VT">
   /*! tailwindcss v3.4.3 | MIT License | https://tailwindcss.com*/*,:after,:before{border:0 solid #e5e7eb;box-sizing:border-box}:after,:before{--tw-content:""}:host,html{line-height:1.5;-webkit-text-size-adjust:100%;font-family:ui-sans-serif,system-ui,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-feature-settings:normal;font-variation-settings:normal;tab-size:4;-webkit-tap-highlight-color:transparent}body{line-height:inherit;margin:0}hr{border-top-width:1px;color:inherit;height:0}abbr:where([title]){-webkit-text-decoration:underline dotted;text-decoration:underline dotted}h1,h2,h3,h4,h5,h6{font-size:inherit;font-weight:inherit}a{color:inherit;text-decoration:inherit}b,strong{font-weight:bolder}code,kbd,pre,samp{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace;font-feature-settings:normal;font-size:1em;font-variation-settings:normal}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:initial}sub{bottom:-.25em}sup{top:-.5em}table{border-collapse:collapse;border-color:inherit;text-indent:0}button,input,optgroup,select,textarea{color:inherit;font-family:inherit;font-feature-settings:inherit;font-size:100%;font-variation-settings:inherit;font-weight:inherit;letter-spacing:inherit;line-height:inherit;margin:0;padding:0}button,select{text-transform:none}button,input:where([type=button]),input:where([type=reset]),input:where([type=submit]){-webkit-appearance:button;background-color:initial;background-image:none}:-moz-focusring{outline:auto}:-moz-ui-invalid{box-shadow:none}progress{vertical-align:initial}::-webkit-inner-spin-button,::-webkit-outer-spin-button{height:auto}[type=search]{-webkit-appearance:textfield;outline-offset:-2px}::-webkit-search-decoration{

In [44]:
import requests
import pandas as pd
from datetime import datetime
import json

def fetch_bmkg_weather_api(adm4_code):
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={adm4_code}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()
        
        # Asumsi data ada di 'data' key, ambil forecast pertama (sesuaikan jika perlu)
        if 'data' in data and data['data']:
            forecast = data['data'][0]  # Ambil hari pertama
            location_info = data.get('lokasi', {})  # Info lokasi
            
            return {
                'city': f"{location_info.get('desa', 'Unknown')}, {location_info.get('kecamatan', '')}",
                'weather_condition': forecast.get('weather_desc', 'N/A'),
                'temperature': f"{forecast.get('t', 'N/A')}°C",
                'humidity': f"{forecast.get('hu', 'N/A')}%",
                'scraped_at': datetime.now().isoformat()
            }
        else:
            print("Data tidak ditemukan")
            return None
    except Exception as e:
        print(f"Error API BMKG: {e}")
        return None

# Contoh penggunaan: Kode wilayah untuk Jakarta Pusat (ganti dengan kode lain)
adm4_code = "31.71.03.1001"  # Kelurahan Kemayoran, Jakarta Pusat
weather_data = fetch_bmkg_weather_api(adm4_code)

if weather_data:
    df = pd.DataFrame([weather_data])
    print(f"Data cuaca untuk {weather_data['city']}")
    print(df)
else:
    print("Gagal mengambil data")

Data cuaca untuk Kemayoran, Kemayoran
                   city weather_condition temperature humidity  \
0  Kemayoran, Kemayoran               N/A       N/A°C     N/A%

                   scraped_at
0  2025-10-06T11:05:01.998042

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

options = Options()
options.headless = True
driver = webdriver.Chrome(options=options)
driver.get("https://www.bmkg.go.id/cuaca/prakiraan-cuaca-indonesia.bmkg")
soup = BeautifulSoup(driver.page_source, 'html.parser')

# Cari elemen cuaca (sesuaikan selector berdasarkan inspect)
weather_cards = soup.find_all('div', class_='weather-item')  # Contoh; ganti dengan class sebenarnya
weather_data = []
for card in weather_cards:
    city = card.find('h3', class_='city-name').text.strip() if card.find('h3', class_='city-name') else 'N/A'
    condition = card.find('.condition').text.strip() if card.find('.condition') else 'N/A'
    temp = card.find('.temp').text.strip() if card.find('.temp') else 'N/A'
    hum = card.find('.humidity').text.strip() if card.find('.humidity') else 'N/A'
    weather_data.append({'city': city, 'weather_condition': condition, 'temperature': temp, 'humidity': hum})

df = pd.DataFrame(weather_data)
print(df.head())
driver.quit()

Empty DataFrame
Columns: []
Index: []

In [4]:
import requests
import pandas as pd
from datetime import datetime
import json

def fetch_bmkg_weather_api(adm4_code, location_name):
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={adm4_code}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()
        
        if 'data' in data and data['data']:
            forecast = data['data'][0]  # Ambil forecast pertama (terdekat)
            return {
                'city': location_name,
                'weather_condition': forecast.get('weather_desc', 'N/A'),
                'temperature': f"{forecast.get('t', 'N/A')}°C",
                'humidity': f"{forecast.get('hu', 'N/A')}%",
                'wind_speed': f"{forecast.get('ws', 'N/A')} km/jam",
                'datetime': forecast.get('local_datetime', 'N/A'),
                'scraped_at': datetime.now().isoformat()
            }
        else:
            print(f"Tidak ada data untuk {location_name}")
            return None
    except Exception as e:
        print(f"Error untuk {location_name}: {e}")
        return None

# Daftar kota besar dengan kode adm4 (contoh; tambah dari CSV jika perlu)
cities = {
    "31.71.03.1001": "Kemayoran, Jakarta Pusat",  # Jakarta
    # "32.21.01.1001": "Cicendo, Bandung",           # Bandung
    # "35.54.07.1001": "Bulak, Surabaya",            # Surabaya
    "12.71.02.1001": "Medan Maimun, Medan",        # Medan
    "73.11.01.1001": "Maros, Makassar"             # Makassar
}

weather_data = []
for code, name in cities.items():
    result = fetch_bmkg_weather_api(code, name)
    if result:
        weather_data.append(result)

df = pd.DataFrame(weather_data)
if not df.empty:
    print(f"Data cuaca untuk {len(df)} kota (diperbarui {datetime.now().strftime('%Y-%m-%d %H:%M')})")
    print(df[['city', 'weather_condition', 'temperature', 'humidity']])
else:
    print("Gagal mengambil data untuk semua kota")

Data cuaca untuk 3 kota (diperbarui 2025-10-06 11:09)
                       city weather_condition temperature humidity
0  Kemayoran, Jakarta Pusat               N/A       N/A°C     N/A%
1       Medan Maimun, Medan               N/A       N/A°C     N/A%
2           Maros, Makassar               N/A       N/A°C     N/A%

Sumber: BMKG (wajib dicantumkan)

In [5]:
df

,city,weather_condition,temperature,humidity,wind_speed,datetime,scraped_at
0,"Kemayoran, Jakarta Pusat",N/A,N/A°C,N/A%,N/A km/jam,N/A,2025-10-06T11:09:58.573793
1,"Medan Maimun, Medan",N/A,N/A°C,N/A%,N/A km/jam,N/A,2025-10-06T11:09:58.683856
2,"Maros, Makassar",N/A,N/A°C,N/A%,N/A km/jam,N/A,2025-10-06T11:09:58.785770

In [7]:
import requests
import pandas as pd
from datetime import datetime

def fetch_bmkg_weather_api(adm4_code, location_name):
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={adm4_code}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()
        
        # Periksa struktur: data['data'][0]['cuaca'][0][0] untuk forecast pertama
        if 'data' in data and data['data'] and data['data'][0].get('cuaca') and data['data'][0]['cuaca'][0]:
            forecast = data['data'][0]['cuaca'][0][0]  # Forecast pertama (hari ini, slot awal)
            return {
                'city': location_name,
                'weather_condition': forecast.get('weather_desc', 'N/A'),
                'temperature': f"{forecast.get('t', 'N/A')}°C",
                'humidity': f"{forecast.get('hu', 'N/A')}%",
                'wind_speed': f"{forecast.get('ws', 'N/A')} km/jam",
                'datetime': forecast.get('local_datetime', 'N/A'),
                'scraped_at': datetime.now().isoformat()
            }
        else:
            print(f"Tidak ada data cuaca untuk {location_name}")
            return None
    except Exception as e:
        print(f"Error untuk {location_name}: {e}")
        return None

# Daftar kota besar dengan kode adm4 (verifikasi dari sumber resmi BMKG)
cities = {
    "31.71.03.1001": "Kemayoran, Jakarta Pusat",      # Jakarta
    # "32.21.01.1001": "Cicendo, Bandung",               # Bandung
    # "35.54.07.1001": "Bulak, Surabaya",                # Surabaya
    "12.71.02.1001": "Medan Maimun, Medan",            # Medan
    "73.11.01.1001": "Maros, Makassar"                 # Makassar (perbaiki jika salah; ini contoh untuk Maros)
}

weather_data = []
for code, name in cities.items():
    result = fetch_bmkg_weather_api(code, name)
    if result:
        weather_data.append(result)

df = pd.DataFrame(weather_data)
if not df.empty:
    print(f"Data cuaca untuk {len(df)} kota (diperbarui {datetime.now().strftime('%Y-%m-%d %H:%M')})")
    print(df[['city', 'weather_condition', 'temperature', 'humidity', 'wind_speed', 'datetime']].to_string(index=False))
else:
    print("Gagal mengambil data untuk semua kota")

Data cuaca untuk 3 kota (diperbarui 2025-10-06 11:13)
                    city weather_condition temperature humidity wind_speed            datetime
Kemayoran, Jakarta Pusat     Cerah Berawan        31°C      60% 8.7 km/jam 2025-10-06 11:00:00
     Medan Maimun, Medan             Cerah        31°C      65% 8.2 km/jam 2025-10-06 12:00:00
         Maros, Makassar      Hujan Sedang        31°C      94% 4.9 km/jam 2025-10-06 13:00:00

Sumber: BMKG (wajib dicantumkan)

In [8]:
df

,city,weather_condition,temperature,humidity,wind_speed,datetime,scraped_at
0,"Kemayoran, Jakarta Pusat",Cerah Berawan,31°C,60%,8.7 km/jam,2025-10-06 11:00:00,2025-10-06T11:13:12.190533
1,"Medan Maimun, Medan",Cerah,31°C,65%,8.2 km/jam,2025-10-06 12:00:00,2025-10-06T11:13:12.322436
2,"Maros, Makassar",Hujan Sedang,31°C,94%,4.9 km/jam,2025-10-06 13:00:00,2025-10-06T11:13:12.525669

In [ ]:
import requests
import pandas as pd
from datetime import datetime

def fetch_bmkg_weather_api(adm4_code, location_name):
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={adm4_code}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()
        
        # Periksa struktur: data['data'][0]['cuaca'][0][0] untuk forecast pertama
        if 'data' in data and data['data'] and data['data'][0].get('cuaca') and data['data'][0]['cuaca'][0]:
            forecast = data['data'][0]['cuaca'][0][0]  # Forecast pertama (hari ini, slot awal)
            return {
                'city': location_name,
                'weather_condition': forecast.get('weather_desc', 'N/A'),
                'temperature': f"{forecast.get('t', 'N/A')}°C",
                'humidity': f"{forecast.get('hu', 'N/A')}%",
                'wind_speed': f"{forecast.get('ws', 'N/A')} km/jam",
                'datetime': forecast.get('local_datetime', 'N/A'),
                'scraped_at': datetime.now().isoformat()
            }
        else:
            print(f"Tidak ada data cuaca untuk {location_name}")
            return None
    except Exception as e:
        print(f"Error untuk {location_name}: {e}")
        return None

# Daftar kota besar dengan kode adm4 (verifikasi dari sumber resmi BMKG)
cities = {
    "31.71.03.1001": "Kemayoran, Jakarta Pusat",      # Jakarta
    # "32.21.01.1001": "Cicendo, Bandung",               # Bandung
    # "35.54.07.1001": "Bulak, Surabaya",                # Surabaya
    "12.71.02.1001": "Medan Maimun, Medan",            # Medan
    "73.11.01.1001": "Maros, Makassar"                 # Makassar (perbaiki jika salah; ini contoh untuk Maros)
}

weather_data = []
for code, name in cities.items():
    result = fetch_bmkg_weather_api(code, name)
    if result:
        weather_data.append(result)

df = pd.DataFrame(weather_data)
if not df.empty:
    print(f"Data cuaca untuk {len(df)} kota (diperbarui {datetime.now().strftime('%Y-%m-%d %H:%M')})")
    print(df[['city', 'weather_condition', 'temperature', 'humidity', 'wind_speed', 'datetime']].to_string(index=False))
else:
    print("Gagal mengambil data untuk semua kota")

In [ ]:
import requests
import pandas as pd
from datetime import datetime

def fetch_bmkg_weather_api(adm4_code, location_name):
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={adm4_code}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()
        
        # Periksa struktur: data['data'][0]['cuaca'][0][0] untuk forecast pertama
        if 'data' in data and data['data'] and data['data'][0].get('cuaca') and data['data'][0]['cuaca'][0]:
            forecast = data['data'][0]['cuaca'][0][0]  # Forecast pertama (hari ini, slot awal)
            return {
                'city': location_name,
                'weather_condition': forecast.get('weather_desc', 'N/A'),
                'temperature': f"{forecast.get('t', 'N/A')}°C",
                'humidity': f"{forecast.get('hu', 'N/A')}%",
                'wind_speed': f"{forecast.get('ws', 'N/A')} km/jam",
                'datetime': forecast.get('local_datetime', 'N/A'),
                'scraped_at': datetime.now().isoformat()
            }
        else:
            print(f"Tidak ada data cuaca untuk {location_name}")
            return None
    except Exception as e:
        print(f"Error untuk {location_name}: {e}")
        return None

# Daftar kota besar dengan kode adm4 (verifikasi dari sumber resmi BMKG)
cities = {
    "31.71.03.1001": "Kemayoran, Jakarta Pusat",      # Jakarta
    "12.71.02.1001": "Medan Maimun, Medan",            # Medan
    "73.11.01.1001": "Maros, Makassar"                 # Makassar (perbaiki jika salah; ini contoh untuk Maros)
}

weather_data = []
for code, name in cities.items():
    result = fetch_bmkg_weather_api(code, name)
    if result:
        weather_data.append(result)

df = pd.DataFrame(weather_data)
if not df.empty:
    print(f"Data cuaca untuk {len(df)} kota (diperbarui {datetime.now().strftime('%Y-%m-%d %H:%M')})")
    print(df[['city', 'weather_condition', 'temperature', 'humidity', 'wind_speed', 'datetime']].to_string(index=False))
else:
    print("Gagal mengambil data untuk semua kota")